FROM golang:1.13-alpine
RUN apk add git curl build-base bash openssh-client shadow

RUN go get github.com/mattn/go-sqlite3 && \
    go install github.com/mattn/go-sqlite3 &&\
    go get -u -v github.com/codeskyblue/fswatch


## Mount src/pingr
SHELL ["/bin/bash", "-c"]
RUN echo -e "desc: re builds go  \n\
triggers:  \n\
  - name: ''  \n\
    pattens: \n\
      - '**/*.go'  \n\
      - '**/*.html'  \n\
      - '**/*.css'  \n\
    env:  \n\
      DEBUG: '1'  \n\
    cmd: go run /go/src/pingr/cmd/pingrd/pingrd.go  \n\
    shell: true  \n\
    delay: 100ms  \n\
    stop_timeout: 500ms  \n\
    signal: KILL  \n\
    kill_signal: 'SIGTERM'  \n\
watch_paths: \n\
  - .  \n\
watch_depth: 10  \n\
" > /fsw.yml



ARG UID
RUN groupadd --gid $UID pingr && useradd --uid $UID --gid pingr --create-home pingr
RUN chown -R pingr:pingr /go
USER pingr
WORKDIR /go/src/pingr

CMD fswatch -config /fsw.yml